# * Make sure to use annotations for eks NLB
# ? for supported annotations: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/
---
apiVersion: v1
kind: Service
metadata:
  name: pf-api
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  selector:
    app: pf-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
