---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::982534378276:role/pumpfactory-eks-stg-us-east-1-myapp-secrets